### ISSUE TITLE
Property 'uri' does not exist on type 'FileWriteResult'

### ISSUE THREAD

**Issue by zechigan** [ionic-team/photo-gallery-capacitor-ng#11]
https://github.com/ionic-team/photo-gallery-capacitor-ng/blob/a7f520e4d48adab8fbaa4ee580480884ca91a293/src/app/services/photo.service.ts#L95

Hi, many thanks for the tutorial. I am trying to implement this on mobile but both line 95 and 96 gives me this error of 'Property 'uri' does not exist on type 'FileWriteResult''. 

Any idea why this happens? Thank you in advance/

**Comment by dotNetkow** [comment]
Hi, this is a new property as of Capacitor 2.0. Are you on that version (check for `@capacitor/core: 2.x`.  Otherwise, see [the 1.0 release](https://github.com/ionic-team/photo-gallery-capacitor-ng/releases/tag/v1.0) of this sample app's code for the original Capacitor 1.x implementation.
