### ISSUE TITLE
Select Image when use on web and not installed camera

### ISSUE THREAD

**Issue by manisi** [ionic-team/photo-gallery-capacitor-ng#12]
Hi, many thanks for the tutorial.
is possible  use select image  file browser when camera not installed .?
Thanks.

**Comment by dotNetkow** [comment]
Sure, but I'll leave that exercise up to you.  :)

[Start here](https://developer.mozilla.org/en-US/docs/Web/API/File/Using_files_from_web_applications).

**Comment by manisi** [comment]
@dotNetkow Thanks :) 👍

**Comment by manisi** [comment]
Sorry Sorry last question, in PWA after using "Add to Home Screen" in safari ,Camera thats ok?
Thanks a lot
:)
