### ISSUE TITLE
Why use platform.ready() ?

### ISSUE THREAD

**Issue by nicobytes** [ionic-team/photo-gallery-capacitor-ng#5]
Hello!

I have a question about init app, in the article about capacitor 1.0 saw:

![Screen Shot 2020-02-02 at 7 01 00 PM](https://user-images.githubusercontent.com/7611944/73616810-6d822480-45ee-11ea-93bd-2647e7ae263b.png)

But in your code use:

```ts
initializeApp() {
    this.platform.ready().then(() => {
      this.statusBar.styleDefault();
      
      SplashScreen.hide();
    });
  }
```

What is the reason? I understand if I use Cordova I must use platform.ready but with Capacitor, it's not necessary.

**Comment by dotNetkow** [comment]
Great question! See [here](https://capacitor.ionicframework.com/docs/apis/splash-screen#hiding-the-splash-screen). I'll add this link to the repo itself as a comment, too.

> To make sure you provide the fastest app loading experience to your users, you must hide the splash screen automatically when your app is ready to be used. Simply add the SplashScreen.hide() call near the top of your app's JS, such as in app.component.ts if using Angular.

**Comment by dotNetkow** [comment]
Apologies - I didn't explain this very well. This was a mistake, we actually don't need the Platform ready() call there, as you mentioned. Calling SplashScreen.hide() is still ok, though. I've updated the code in the "v5-migration" branch, shipping soon :)
