### ISSUE TITLE
Error in electron

### ISSUE THREAD

**Issue by nicobytes** [ionic-team/photo-gallery-capacitor-ng#6]
I try add electron with this steps:

1. `ionic build --prod`
2. `ionic cap add electron`
3. `ionic cap copy`
4. `ionic cap open electron`

And show this error:

![Screen Shot 2020-02-02 at 7 35 37 PM](https://user-images.githubusercontent.com/7611944/73617278-5134b680-45f3-11ea-8ad5-49e2135dfb1f.png)

**Comment by dotNetkow** [comment]
Thanks, I can confirm the issue. This guide was designed for web, ios and android but should work (at least, build and run) with Electron. I'll log a Capacitor issue.

**Comment by jcesarmobile** [comment]
The problem is angular not working fine if served from file:// protocol.

If you build setting the base href to `./` it will work `ionic build --prod -- --base-href=./`
