### ISSUE TITLE
Update jasmine-core

### ISSUE THREAD

**Issue by kklamberty** [ionic-team/photo-gallery-capacitor-ng#8]
When running the command `ionic start photo-gallery tabs --type=angular --capacitor` from the tutorial, the `package.json` in the `photo-gallery` folder has `jasmine-core` at 3.4, which gives an npm warning because 3.5 is needed. Updating that number to 3.5 mitigates the warning.

**Comment by dotNetkow** [comment]
Thanks for this - updated just now with migration to Capacitor 2.0. Cheers.
